name: 'dbt_transformation'
version: '1.0.0'
config-version: 2


profile: 'dbt_transformation'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_transformation:
    staging:
      +materialized: view
      +schema: de_smartphone_staging
    marts:
      +materialized: table
      +schema: de_smartphone_marts


